//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStoreManagementSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketProducts
    {
        public int idBasket { get; set; }
        public int idProduct { get; set; }
        public int Count { get; set; }
        public int Price { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Products Products { get; set; }
    }
}
