//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStoreManagementSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int idOrder { get; set; }
        public int idUser { get; set; }
        public int idStatus { get; set; }
        public int idPoint { get; set; }
    
        public virtual AdressPoints AdressPoints { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
