//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStoreManagementSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int idReport { get; set; }
        public string PopularProduct { get; set; }
        public string ActiveUser { get; set; }
        public int TotalRevenues { get; set; }
    }
}
